---
title: "Bug Hotels"
author: "Gregory J. Matthews"
date: "2024-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE, message = FALSE}
library(rjags)
library(ggmosaic)
library(tidyverse)
cong <- read.csv("/Users/gregorymatthews/Dropbox/bug_hotels/data/cong_master.csv")

#Remove the DO outliers
cong <- cong %>% filter(DO_mg_L <= 20)

cong <- cong %>% select(Date, Site, Plot, Week, Treatment, Lat, Long,
                        Inv_abun, Collector, Shredder, Piercer, Scraper, Predator,DO_mg_L )

cong <- cong %>% mutate(n_col = Inv_abun*Collector,
                        n_shr = Inv_abun*Shredder,
                        n_pie = Inv_abun*Piercer,
                        n_scr = Inv_abun*Scraper,
                        n_pre = Inv_abun*Predator)


cong$Treatment <- as.factor(cong$Treatment)

#Checking
tot <- cong %>% group_by(Treatment) %>% summarize(sum_n_col = sum(n_col),
                                                  sum_n_shr = sum(n_shr),
                                                  sum_n_pie = sum(n_pie),
                                                  sum_n_scr = sum(n_scr),
                                                  sum_n_pre = sum(n_pre)) 
tot[,-1] <- t(apply(tot[,-1],1,function(x){x/sum(x)}))
```

```{r}
rownames <- tot$Treatment
tab <-tot[,-1] %>% as.matrix() %>% as.table()
row.names(tab) <- c(rownames)
#Rows and columns are not independent
chisq.test(tab)
```

# Some EDA stuff 
```{r}
#Data viz
ggdat <- cong %>% select(Treatment, n_col, n_shr, n_pie, n_scr, n_pre) %>% pivot_longer(names_to = "Category", cols = c("n_col","n_shr","n_pie","n_scr","n_pre"))
ggplot(aes(fill = Category, x = Treatment, y = value), data = ggdat) + geom_bar(position="fill", stat="identity")
```


```{r}
#EDA
names(cong)
table(cong$Date)
table(cong$Site) #All Munuscong
table(cong$Plot)
table(cong$Week)
table(cong$Week, cong$Plot) #Why is MEAD 4 and 5 not repeated?  
table(cong$Treatment)
summary(cong$Inv_abun)
summary(cong$Collector)

cong %>% group_by(Treatment) %>% summarize()

```




```{r echo = FALSE}
#Bayes stuff
cong  <- cong %>% mutate(I_meadow = ifelse(Treatment == "meadow",1,0),
                         I_submerged = ifelse(Treatment == "submerged",1,0),
                         I_tyhyd = ifelse(Treatment == "tyhyd",1,0),
                         I_typha = ifelse(Treatment == "typha",1,0),
                         I_week = ifelse(Week == "W1",0,1))
Y <- cong %>% select(n_col, n_shr, n_pie, n_scr, n_pre) 
Y <- as.matrix(Y)
Y <- matrix(as.integer(Y),nrow = nrow(Y), ncol = ncol(Y))
#Creating the design matrix
#Meadow is baseline
X <- cong %>% select(I_submerged, I_tyhyd, I_typha,DO_mg_L, I_week)
#X <- cong %>% select(I_meadow,I_submerged, I_tyhyd, I_typha,DO_mg_L)
X <- data.frame(int = 1,as.matrix(X))

Z <- matrix(NA, nrow = nrow(cong), ncol = length(unique(cong$Plot)))
for (i in 1:nrow(cong)) {
  for (j in 1:length(unique(cong$Plot))) {
    Z[i, j] <- ifelse(sort(unique(cong$Plot))[j] == cong$Plot[i], 1, 0)
  }
}  
n <- apply(Y, 1, sum)
```

```{r eval = FALSE}
library(rjags)
####################################
#Fixed and random effects
####################################
data <- list(
  N = nrow(Y), # Number of observations
  J = ncol(Y),        # Number of classes
  Dx = ncol(X),  #Number of columns of X
  Dz = ncol(Z), #Number of columns of Z
  Y = Y,     # Response variable
  X = X,      #Predictor matrix Fixed effects
  Z = Z,     #predictor matrix Random effects
  n = n     #number of total bugs at each site
)

model_string <- "
model{

for (i in 1:N){
  Y[i,] ~ dmulti(p[i,], n[i])

for (j in 1:(J-1)){
  p[i,j] <- theta[i,j]/(1+sum(theta[i,]))
}
  p[i,J] <- 1/(1+sum(theta[i,]))

  for (j in 1:(J-1)){
  theta[i,j] <- exp(inprod(X[i,], beta[,j]) + inprod(Z[i,], b[,j]))
  }
 
 
 
}
 
 
for (d in 1:Dx) {
  for (j in 1:(J-1)){
    beta[d, j] ~ dnorm(0, 0.001)
  }
}

for (d in 1:Dz) {
  for (j in 1:(J-1)){
    b[d, j] ~ dnorm(0, tau2b)
  }
}

tau2b <- 1/sigma2b
sigma2b ~  dnorm(0, 0.001)T(0,10000)
 
 


}"


setwd("/Users/gregorymatthews/Dropbox/CDSC/bug_hotels/")
write(model_string,"bug_hotels.bug")

# Run JAGS
jags <- jags.model("/Users/gregorymatthews/Dropbox/CDSC/bug_hotels/bug_hotels.bug",
                   data = data,
                   n.chains = 3, 
                   n.adapt = 100
)

update(jags, 1000)

ztest <- jags.samples(jags,c('beta','p','b',"sigma2b"),1000, thin = 1)
z <- jags.samples(jags,c('beta','p','b',"sigma2b"),200000, thin = 200)

#save(z, file = "/Users/gregorymatthews/Dropbox/bug_hotels/z.RData")

```

```{r echo = FALSE}
load("/Users/gregorymatthews/Dropbox/bug_hotels/z.RData")
```

# Posterior estimates for $\beta$
```{r echo = FALSE}
datbeta <- data.frame(treatment = rep(c("submerged","typhd","typha"), each = 4*3000), 
                   category = rep(c("p_col", "p_shr", "p_pie", "p_scr"),each = 3000),
    beta = c(c(z$beta[2,1,,1],z$beta[2,1,,2],z$beta[2,1,,3]),
           c(z$beta[2,2,,1],z$beta[2,2,,2],z$beta[2,2,,3]),
           c(z$beta[2,3,,1],z$beta[2,3,,2],z$beta[2,3,,3]),
           c(z$beta[2,4,,1],z$beta[2,4,,2],z$beta[2,4,,3]),
           c(z$beta[3,1,,1],z$beta[3,1,,2],z$beta[3,1,,3]),
           c(z$beta[3,2,,1],z$beta[3,2,,2],z$beta[3,2,,3]),
           c(z$beta[3,3,,1],z$beta[3,3,,2],z$beta[3,3,,3]),
           c(z$beta[3,4,,1],z$beta[3,4,,2],z$beta[3,4,,3]),
           c(z$beta[4,1,,1],z$beta[4,1,,2],z$beta[4,1,,3]),
           c(z$beta[4,2,,1],z$beta[4,2,,2],z$beta[4,2,,3]),
           c(z$beta[4,3,,1],z$beta[4,3,,2],z$beta[4,3,,3]),
           c(z$beta[4,4,,1],z$beta[4,4,,2],z$beta[4,4,,3]))
           
    )


ggplot(aes(x = beta), data = datbeta) + geom_density() + facet_grid(treatment ~ category) + geom_vline(xintercept = 0) 
  

```

# Posterior probablities for $\beta > 0$

```{r}
summ <- datbeta %>% group_by(treatment, category) %>% summarize(mean(beta > 0))
summ
```

# Posterior estimates for p

```{r echo = FALSE}
#Plot with 4 rows for each Treatment.  
#And then posterior density plots for each of the categories.
#Using the average level of the random effect, Average Do_mg_L, and Week 0.  
#Find p vectors with average levels 
newX <- X[1:4,]
newX$DO_mg_L <- mean(X$DO_mg_L)
diag(newX[2:4,2:4]) <- 1

#4 treatments, 5 categories 
results1 <- results2 <- results3 <- list()
for (i in 1:1000){
  results1[[i]] <-
    data.frame(category = rep(c("p_col", "p_shr", "p_pie", "p_scr", "p_pre"),4),                treatment = rep(c("meadow","submerged","typhd","typha"),each = 5),
               p = c(apply(cbind(exp(as.matrix(newX) %*% z$beta[,,i,1]),1),1,function(x) {x / sum(x)})))

results2[[i]] <- data.frame(category = rep(c("p_col", "p_shr", "p_pie", "p_scr", "p_pre"),4),                treatment = rep(c("meadow","submerged","typhd","typha"),each = 5),
               p = c(apply(cbind(exp(as.matrix(newX) %*% z$beta[,,i,1]),2),1,function(x) {x / sum(x)})))

results3[[i]] <- data.frame(category = rep(c("p_col", "p_shr", "p_pie", "p_scr", "p_pre"),4),                treatment = rep(c("meadow","submerged","typhd","typha"),each = 5),
               p = c(apply(cbind(exp(as.matrix(newX) %*% z$beta[,,i,3]),1),1,function(x) {x / sum(x)})))
}

results <- rbind(do.call(rbind,results1),do.call(rbind,results2),do.call(rbind,results3))

ggplot(aes(x = p, y = after_stat(scaled), color = category), data = results) + geom_density() + facet_grid(treatment ~ 1)
```

# Posterior probabilities for p
```{r}
d <- data.frame()
for (cat in c("p_col", "p_shr", "p_pie", "p_scr","p_pre")){
  for (trt in c("submerged","typha","typhd")){
prob <- mean((results %>% filter(category == cat & treatment == "meadow")  %>% select(p))  > (results %>% filter(category == cat & treatment == trt) %>% select(p)))
d <- rbind(d, data.frame(category = cat, 
                         treatment = trt, 
                         prob = prob))
  }}

d
```

# Posterior means and 95% credible intervals for p
```{r}
#Posterior means with 95% credible intervals
results %>% 
  group_by(category, treatment) %>% 
  summarize(mean = mean(p), lower = quantile(p, 0.025), upper = quantile(p, 0.975))

#Posterior means
test <- results %>% 
  group_by(category, treatment) %>% 
  summarize(mean = mean(p)) %>% pivot_wider(names_from = category, values_from = mean) 
```

# Varibility between different plots.  
```{r}
ggdat <- data.frame(sigma2b = c(z$sigma2b[,,1],z$sigma2b[,,2],z$sigma2b[,,3]))
ggplot(aes(x = sigma2b), data = ggdat) + geom_density() 
```

# Appendix

```{r}
#Check convergence. 
conv <- data.frame(iter = rep(1:1000, 3), chain = rep(1:3,each = 1000), sigma2b = c(z$sigma2b[1,,1],z$sigma2b[1,,2],z$sigma2b[1,,3]))
ggplot(aes(x = iter, y = sigma2b, color = factor(chain)),data = conv) + geom_path()

for (i in 1:10){
  for (j in 1:5){
conv <- data.frame(iter = rep(1:1000, 3), chain = rep(1:3,each = 1000), p = c(z$p[i,j,,1],z$p[i,j,,2],z$p[i,j,,3]))
g <- ggplot(aes(x = iter, y = p, color = factor(chain)),data = conv) + geom_path() + ggtitle(paste("i = ",i," j = ",j))
print(g)
}}


#Check ACF plots.
acf(z$sigma2b[1,,1])

for (i in 1:10){
  for (j in 1:5){
acf(z$p[i,j,,1])
    }}

```